AC|AC (Acre)|AC
AL|AL (Alagoas)|AL
AP|AP (Amapá)|AP
AM|AM (Amazonas)|AM
BA|BA (Bahia)|BA
CE|CE (Ceará)|CE
DF|DF (Distrito Federal)|DF
ES|ES (Espírito Santo)|ES
GO|GO (Goiás)|GO
MA|MA (Maranhão)|MA
MT|MT (Mato Grosso)|MT
MS|MS (Mato Grosso do Sul)|MS
MG|MG (Minas Gerais)|MG
PA|PA (Pará)|PA
PB|PB (Paraíba)|PB
PR|PR (Paraná)|PR
PE|PE (Pernambuco)|PE
PI|PI (Piauí)|PI
RJ|RJ (Rio de Janeiro)|RJ
RN|RN (Rio Grande do Norte)|RN
RS|RS (Rio Grande do Sul)|RS
RO|RO (Rondônia)|RO
RR|RR (Roraima)|RR
SC|SC (Santa Catarina)|SC
SP|SP (São Paulo)|SP
SE|SE (Sergipe)|SE
TO|TO (Tocantins)|TO