Вес|Вес|кг
Объем|Объем|m3
НДС|НДС|%
Подраздел3|Подраздел3|
Подраздел4|Подраздел4|
Meta Title|Meta Title|
Meta Description|Meta Description|
Meta Keywords|Meta Keywords|
Минимальный заказ|Минимальный заказ|шт.
g:country|Shipping country|
g:service|Shipping service|
g:price|Shipping Price|
g:google_product_category|Product category|
g:product_type|Product type|
g:gtin|EAN|
g:attach|ATT|
g:aoption|AO| 
