Russia|Россия|7
Ukraine|Украина|380
Afghanistan|Афганистан|93
Albania|Албания|355
Algeria|Алжир|21
American Samoa|Американское Самоа|684
Andorra|Андорра|376
Angola|Ангола|244
Anguilla|Ангуилла |1-264
Antigua and Barbuda|Антигуа и Барбуда|1-268
Argentina|Аргентина|54
Armenia|Армения|374
Aruba|Аруба|297
Ascension|Асеньон|247
Australia|Австралия|61
Australian External Territories|Австралийские внеш. террит-и|672
Austria|Австрия|43
Azerbaijan|Азербайджан|994
Azores|Азорские о-ва|351
Bahamas|Багамы|1-242
Bahrain|Бахрейн|973
Bangladesh|Бангладеш|880
Barbados|Барбадос|1-246
Belarus|Белоруссия|375
Belgium|Бельгия|32
Belize|Белиз|501
Benin|Бенин|229
Bermuda|Бермудские о-ва|1-441
Bhutan|Бутан|975
Bolivia|Боливия|591
Bosnia and Herzegovina|Босния и Герцеговина|387
Botswana|Ботсвана|267
Brazil|Бразилия|55
British Virgin Islands|Британские Вирджинские о-ва|1-284
Brunei|Бруней|673
Bulgaria|Болгария|359
Burkina Faso|Буркина Фасо|226
Burundi|Бурунди|257
Cambodia|Камбоджа|855
Cameroon|Камерун|237
Cape Verde|Капе Верде|238
Cayman Islands|Каймановы о-ва|1-345
Central African Republic|ЦАР|236
Chad|Чад|235
Chile|Чили|56
China|Китай|86
Christmas Island|Рождественсткие о-ва|672
Cocos Islands|Кокосовые о-ва|672
Colombia|Колумбия|57
Commonwealth of the Northern Mariana Islands|Содружество северных Марианских о-вов|1-670
Comoros and Mayotte Island|Коморские о-ва|269
Congo|Конго|242
Democratic Republic of Congo (ex. Zaire)|Дем. респ. Конго (бывш. Заир)|243
Cook Islands|О-ва Кука|682
Costa Rica|Коста Рика|506
Croatia|Хорватия|385
Cuba|Куба|53
Cyprus|Кипр|357
Czech Republic|Чехия|420
Denmark|Дания|45
Diego Garcia|Диего Гарсиа|246
Djibouti|Джибути|253
Dominica|Доминика|1-767
Dominican Republic|Доминиканская республика|1-809
East Timor|Восточный Тимор|62
Ecuador|Эквадор|593
Egypt|Египет|20
El Salvador|Сальвадор|503
Equatorial Guinea|Экваториальная Гвинея|240
Eritrea|Эритрия|291
Estonia|Эстония|372
Ethiopia|Эфиопия|251
Faeroe Islands|Фарерские о-ва|298
Falkland Islands|Фолклендские о-ва|500
Fiji|Фиджи|679
Finland|Финляндия|358
France|Франция|33
French Antilles|Французские Антиллы|590
French Guiana|Французская Гвиана|594
French Polynesia|Французская полинезия|689
Gabonese Republic|Габон|241
Gambia|Гамбия|220
Georgia|Грузия|995
Germany|Германия|49
Ghana|Гана|233
Gibraltar|Гибралтар|350
Greece|Греция|30
Greenland|Гренландия|299
Grenada|Гренада|1-473
Guam|Гуам|671
Guatemala|Гватемала|502
Guinea|Гвинея|224
Guinea-Bissau|Гвинея Биссау|245
Guyana|Гайана|592
Haiti|Гаити|509
Honduras|Гондурас|504
Hong Kong|Гонконг|852
Hungary|Венгрия|36
Iceland|Исландия|354
India|Индия|91
Indonesia|Индонезия|62
Iran|Иран|98
Iraq|Ирак|964
Irish Republic|Ирландия|353
Israel|Израиль|972
Italy|Италия|39
Ivory Coast|Берег слоновой кости|225
Jamaica|Ямайка|1-876
Japan|Япония|81
Jordan|Иордания|962
Kazakhstan|Казахстан|7-10
Kenya|Кения|254
Kiribati Republic|Кирибати|686
Korea, Dem. People's Republic|Северная Корея|850
Korea, Republic|Южная Корея|82
Kuwait|Кувейт|965
Kyrgyzstan|Киргизстан|996
Laos|Лаос|856
Latvia|Латвия|371
Lebanon|Ливан|961
Lesotho|Лессото|266
Liberia|Либерия|231
Libya|Ливия|21
Liechtenstein|Лихтенштейн|41
Lithuania|Литва|370
Luxembourg|Люксембург|352
Macau|Макао|853
Macedonia|Македония|389
Madagascar|Мадагаскар|261
Malawi|Малави|265
Malaysia|Малайзия|60
Maldives|Мальдивские о-ва|960
Mali|Мали|223
Malta|Мальта|356
Marshall Islands|Маршалловы о-ва|692
Martinique|Мартиника|596
Mauritania|Мавритания|222
Mauritius|Маврикий|230
Mexico|Мексика|52
Micronesia|Микронезия|691
Monaco|Монако|377
Mongolia|Монголия|976
Montserrat|Монсеррат|1-664
Moldova|Молдавия|373
Morocco|Марокко|212
Mozambique|Мозамбик|258
Myanmar|Мьянма|95
Namibia|Намибия|264
Nauru|Науру|674
Nepal|Непал|977
Netherlands|Нидерланды|31
Netherlands Antilles|Нидерландские Антиллы|599
New Caledonia|Новая Каледония|687
New Zealand|Новая Зеландия|64
Nicaragua|Никарагуа|505
Niger|Нигер|227
Nigeria|Нигерия|234
Niue Islands|Нию о-ва|683
Norfolk Island|Норфолкские о-ва|672
Northern Mariana Islands|Северо-Марианские о-ва|670
Norway|Норвегия|47
Oman|Оман|968
Pakistan|Пакистан|92
Palau|Палау|680
Panama|Панама|507
Papua New Guinea|Папуа Новая Гвинея|675
Paraguay|Парагвай|595
Peru|Перу|51
Philippines|Филипины|63
Poland|Польша|48
Portugal|Португалия|351
Puerto Rico|Пуэрто Рико|1-787
Qatar|Катар|974
Republic of San Marino|Респ. Сан Марино|378
Reunion Islands|Реюнион|262
Romania|Румыния|40
Rwandese Republic|Руанда|250
Saint Helena and Ascension Island|О-ва Святой Елены|247
Saint Pierre et Miquelon|Сент Пьер|508
San Marino|Сан Марино|39
Sao Tome e Principe|Сент Том и Принцип|239
Saudi Arabia|Саудовская Аравия|966
Senegal|Сенегал|221
Seychelles|Сейшельские о-ва|248
Sierra Leone|Сьерра Леоне|232
Singapore|Сингапур|65
Slovak Republic|Словакия|421
Slovenia|Словения|386
Solomon Islands|Соломоновы о-ва|677
Somalia|Сомали|252
South Africa|ЮАР|27
Spain|Испания|34
Sri Lanka|Шри Ланка|94
St. Kitts and Nevis|Сент-Китс и Невис|1-869
St. Lucia|Санта Лючия|1-758
St. Vincent and the Grenadines|Сент Винцент и Гренадины|1-784
Sudan|Судан|249
Suriname|Суринам|597
Svalbard and Jan Mayen Islands|Свалбард|47
Swaziland|Свазиленд|268
Sweden|Швеция|46
Switzerland|Швейцария|41
Syria|Сирия|963
Taiwan|Тайвань|886
Tajikistan|Таджикистан|992
Tanzania|Танзания|255
Thailand|Тайланд|66
Togolese Republic|Тоголезе|228
Tokelau|Токелау|690
Tonga|Тонго|676
Trinidad and Tobago|Тринидад и Тобаго|1-868
Tunisia|Тунис|21
Turkey|Турция|90
Turkmenistan|Туркменистан|993
Tuvalu|Тувалу|688
Uganda|Уганда|256
United Arab Emirates|ОАЭ|971
United Kingdom|Великобритания|44
Uruguay|Уругвай|598
US Virgin Islands|Вирджинские о-ва|1-340
USА|США|1
Uzbekistan|Узбекистан|998
Vanuatu|Вануату|678
Vatican City State|Ватикан|39
Venezuela|Венесуэла|58
Vietnam|Вьетнам|84
Wallis and Futuna|Волис и Фотуна|681
Western Sahara|Западная Сахара|21
Western Samoa|Западное Самоа|685
Yemen, North|Северный Йемен|967
Yemen, South|Южный Йемен|969
Yugoslavia|Югославия|381
Zaire|Заир|243
Zambia|Замбия|260
Zanzibar|Занзибар|259
Zimbabwe|Зимбабве|263
