<div align="center">
<table style="border-collapse: separate;" width="100%" cellspacing="0" cellpadding="3" bordercolor="#000000" border="0"><tbody><tr><td valign="top" colspan="2">
<div>Заказчик: <strong>[prop] [metro]</strong><strong><br>
</strong></div></td><td width="25%" valign="top">
<div>
Счет №:&nbsp;<strong>[nums] </strong></div></td><td width="25%" valign="top">
Дата: <strong>[date] </strong></td></tr><tr><td valign="top" rowspan="1" colspan="4">
<div> <strong></strong>Контактное лицо: <strong>[fio]</strong> Тел: <strong>[telcode] [tel]</strong>[other]<br>
Способ получения: <strong>[Транспортная компания] </strong></div> </td></tr></tbody></table><strong>
<table style="border-collapse: collapse;" width="100%" cellspacing="0" cellpadding="3" bordercolor="#000000" border="1"><tbody><tr><td valign="top" align="center">№</td><td valign="top" align="center">Наименование<br>
</td><td valign="top" align="center">
Кол-во<br>
</td><td valign="top" align="center">
Цена<br>
</td><td valign="top" align="center">
Сумма<br>
</td></tr><!--[tr]--><tr><td valign="top" align="center">
[num]</td><td valign="top" align="left">
[desc]</td><td valign="top" align="center">
[qty] [pcs]</td><td valign="top" align="center">
[price][valut]</td><td valign="top" align="center">
[total][valut]</td></tr><!--[/tr]--></tbody></table></strong></div>
<div align="center">
<div align="right"><strong></strong><br>
Всего к оплате:<font size="4"> [summa]</font>[valut]<strong> </strong><br>
</div>М.П.<br>
<div align="right">
<table width="100%" cellspacing="0" cellpadding="3" bordercolor="#000000" border="0"><tbody><tr><td width="50%" valign="top">
<div>&nbsp;Дата получения: ________________</div></td><td width="50%" valign="top" align="right">
[fio]&nbsp; &nbsp;&nbsp; /_______________</td></tr><tr><td width="50%" valign="top" colspan="1">
<div>&nbsp;</div></td><td width="50%" valign="top" align="right" colspan="1"><font size="1">подпись&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
</font></td></tr></tbody></table><br>
</div></div>