<style type="text/css">.border {border-bottom: 1px solid black; margin-bottom:-0.2em; padding-bottom: 0px; }</style>
<div align="center">
<table style="border-right: black 1px solid; border-top: black 1px solid; border-left: black 1px solid; border-bottom: black 1px solid; max-width: 750px;" cellspacing="0" cellpadding="0" border="0">
<tbody>
<tr valign="top">
<td style="padding-right: 5px; padding-left: 5px; font-size: 11pt; padding-bottom: 5px; padding-top: 5px;" align="center">
<div>Извещение</div>
<div style="margin-top: 12em;">Кассир</div></td>
<td style="border-right: black 1px solid;" width="1" bgcolor="#000000" height="250">
<div style="width: 1px; height: 250px;"></div></td>
<td style="padding-right: 5px; padding-left: 5px; font-size: 10pt; padding-bottom: 5px; padding-top: 5px;">
<div style="font-size: 6pt; float: right;">Форма №ПД-4</div><br clear="all">
<div class="border"><i>[poluchatel]</i></div>
<div style="font-size: 8pt; padding-top: 0px;" align="center">получатель платежа</div>
<div style="float: left; margin-right: 20pt;">
<div class="border"><i>[bank]</i></div>
<div style="font-size: 8pt;" align="center">наименование банка</div></div>
<div style="float: right;">
<div class="border"><i>[rs]  </i></div>
<div style="font-size: 8pt;" align="center">расчетный счет</div></div><br clear="all">
<div style="font-size: 8pt;" class="border"><i>К/с №[ks] БИК [bik]</i></div>
<div style="font-size: 8pt;" align="center">другие банковские реквизиты</div>
<div class="border" align="center"><i>[fio]</i></div>
<div style="font-size: 8pt;" align="center">ФИО плательщика</div>
<div style="font-size: 7pt;" class="border" align="center"><i>[adres]</i></div>
<div style="font-size: 8pt;" align="center">адрес плательщика</div>
<div class="border" align="center"><i>[nums]</i></div>
<div style="font-size: 8pt;" align="center">наименование платежа</div>
<div><span style="font-size: 8pt;">Сумма платежа </span><span class="border"><i>[summa]</i> [valut]</span></div><br>
<div style="font-size: 8pt;">Подпись<br>
плательщика</div></td></tr>
<tr>
<td style="border-top: black 1px solid;" align="right" width="190" bgcolor="#000000">
<div style="width: 190px; height: 1px;"></div></td>
<td></td>
<td style="border-top: black 1px solid;" bgcolor="#000000">
<div style="width: 200px; height: 1px;"></div></td></tr>
<tr>
<td style="padding-right: 5px; padding-left: 5px; font-size: 11pt; padding-bottom: 5px; padding-top: 5px;" valign="bottom" align="center">
<div>Квитанция</div>
<div style="margin-top: 1em;">Кассир</div></td>
<td style="border-right: black 1px solid;" width="1" bgcolor="#000000" height="250">
<div style="width: 1px; height: 250px;"></div></td>
<td style="padding-right: 5px; padding-left: 5px; font-size: 10pt; padding-bottom: 5px; padding-top: 5px;">
<div style="font-size: 6pt; float: right;">Форма №ПД-4</div><br clear="all">
<div class="border"><i>[poluchatel]</i></div>
<div style="font-size: 8pt; padding-top: 0px;" align="center">получатель платежа</div>
<div style="float: left; margin-right: 20pt;">
<div class="border"><i>[bank]</i></div>
<div style="font-size: 8pt;" align="center">наименование банка</div></div>
<div style="float: right;">
<div class="border"><i>[rs]  </i></div>
<div style="font-size: 8pt;" align="center">расчетный счет</div></div><br clear="all">
<div style="font-size: 8pt;" class="border"><i>К/с №[ks] БИК [bik]</i></div>
<div style="font-size: 8pt;" align="center">другие банковские реквизиты</div>
<div class="border" align="center"><i>[fio]</i></div>
<div style="font-size: 8pt;" align="center">ФИО плательщика</div>
<div style="font-size: 7pt;" class="border" align="center"><i>[adres]</i></div>
<div style="font-size: 8pt;" align="center">адрес плательщика</div>
<div class="border" align="center"><i>[nums]</i></div>
<div style="font-size: 8pt;" align="center">наименование платежа</div>
<div><span style="font-size: 8pt;">Сумма платежа </span><span class="border"><i>[summa]</i> [valut]</span></div><br>
<div style="font-size: 8pt;">Подпись<br>
плательщика</div></td></tr></tbody></table></div>
