<div align="center"><font size="6"><strong>[shopname]</strong></font></div>
<div align="center"><font size="4">[poluchatel]</font><br>
[shopadress] [shop_tel]<br>
<br>
<table style="border-collapse: separate;" width="80%" cellspacing="0" cellpadding="3" bordercolor="#000000" border="0"><tbody><tr><td width="25%" valign="top">
<div>Herr(Frau): </div></td><td width="25%" valign="top">
<div>&nbsp;</div></td><td width="25%" valign="top">
<div>
Rechnung / Nr.:&nbsp;</div></td><td width="25%" valign="top">
<div><strong>[nums] </strong><br>
</div></td></tr><tr><td valign="top" colspan="2" rowspan="2">
<div> <strong>[fio] </strong></div></td><td width="25%" valign="top">
<div>Bestelldatum : <br>
</div></td><td width="25%" valign="top">
<div><strong>[date] </strong><br>
</div></td></tr><tr><td width="25%" valign="top">
<div>Bestell / Num.: <br>
</div></td><td width="25%" valign="top">
<div>&nbsp;</div></td></tr><tr><td width="25%" valign="top">
<div>Lief.Adresse: <br>
</div></td><td width="25%" valign="top">
<div>&nbsp;</div></td><td width="25%" valign="top">
<div>Kunden / Num.: <br>
</div></td><td width="25%" valign="top">
<div>&nbsp;</div></td></tr><tr><td valign="top" colspan="2">
<div><strong>[adres]</strong></div></td><td width="25%" valign="top" colspan="1">
<div>&nbsp;</div></td><td width="25%" valign="top" colspan="1">
<div>&nbsp;</div></td></tr></tbody></table><br>
<strong></strong><strong>
<table style="border-collapse: collapse;" width="90%" cellspacing="0" cellpadding="3" bordercolor="#000000" border="1"><tbody><tr><td valign="top" align="center">
Pos</td><td valign="top" align="center">
Artikel / Num.</td><td valign="top" align="center">Beschreibung<br>
</td><td valign="top" align="center">
Menge <br>
</td><td valign="top" align="center">
Einzelpreis <br>
</td><td valign="top" align="center">
Gesamtpreis <br>
</td><td valign="top" align="center">
MwSt <br>
</td></tr><!--[tr]--><tr><td valign="top" align="center">
[num]</td><td valign="top" align="left">
[art]</td><td valign="top" align="left">
[desc]</td><td valign="top" align="center">
[qty][pcs]</td><td valign="top" align="center">
[price][valut]</td><td valign="top" align="center">
[total][valut]</td><td valign="top" align="center">
[nds]</td></tr><!--[/tr]--></tbody></table></strong><strong></strong></div>
<div align="center"><strong><br>
<br>
</strong><strong>
<table style="border-collapse: collapse;" width="90%" cellspacing="0" cellpadding="3" bordercolor="#000000" border="1"><tbody><tr><td valign="top">
<div align="right"></div>
<div>
<div align="right"></div>
<table style="border-collapse: separate;" width="100%" cellspacing="0" cellpadding="3" bordercolor="#000000" border="0"><tbody><tr><td width="30%" valign="top" align="left">
Zahlungsart: <br>
</td><td width="70%" valign="top" rowspan="3">
<div>[payment_type] <br>
</div></td></tr><tr align="left"><td valign="top" colspan="1">&nbsp;</td></tr><tr align="left"><td valign="top" colspan="1">&nbsp;</td></tr><tr><td valign="top" align="left">Lieferdatum:</td><td width="70%" valign="top" rowspan="3">
<div>[delivery_type] <br>
</div></td></tr><tr align="left"><td valign="top" colspan="1">&nbsp;</td></tr><tr align="left"><td valign="top" colspan="1">&nbsp;</td></tr></tbody></table></div></td><td width="50%" valign="top">
<div align="right"></div>
<div>
<div align="right"></div>
<table style="border-collapse: separate;" width="100%" cellspacing="0" cellpadding="3" bordercolor="#000000" border="0"><tbody><tr><td width="50%" valign="top" align="left">
Lieferkosten / Geb&#252;ren: <br>
</td><td width="50%" valign="top" align="right">
[delivery_cost]</td><td valign="top">
<div>[valut]</div></td></tr><tr><td width="50%" valign="top" align="left">
Gesamtpreis netto: <br>
</td><td width="50%" valign="top" align="right">
[totalweight]</td><td valign="top">
<div>[kg] <br>
</div></td></tr><tr><td width="50%" valign="top" align="left">
MwSt&nbsp;&nbsp; [taxrate] <br>
</td><td width="50%" valign="top" align="right">
[tax]</td><td valign="top">
<div>[valut] <br>
</div></td></tr><tr><td width="50%" valign="top" align="left">&nbsp;</td><td width="50%" valign="top" align="right">&nbsp;</td><td valign="top">
<div>&nbsp;</div></td></tr><tr><td width="50%" valign="top" align="left">&nbsp;</td><td width="50%" valign="top" align="right">&nbsp;</td><td valign="top">
<div>&nbsp;</div></td></tr><tr><td width="50%" valign="top" align="left">
Rechnungsendbetrag: <br>
</td><td width="50%" valign="top" align="right">
[summa]<br>
</td><td valign="top">
<div>[valut] <br>
</div></td></tr></tbody></table></div></td></tr></tbody></table>&nbsp;</strong></div><br><div class="text14">
<table style="border: 1px solid rgb(0, 0, 0);" width="720" cellspacing="0" cellpadding="0" bordercolor="#000000"><tbody><tr><td width="220" valign="top" height="250" align="center">&nbsp;<strong>Платеж</strong></td><td valign="top">
<li><strong>Получатель: </strong> <span style="font-size: 90%;"><u>[poluchatel]</u></span>&nbsp;&nbsp;&nbsp;<br>
</li>
<li><strong>КПП:</strong> <u>[kpp]</u>&nbsp;&nbsp;&nbsp;&nbsp; <strong>ИНН:</strong> <u>[inn]</u>&nbsp;&nbsp;&nbsp;&nbsp; <strong>Код ОКАТО:</strong> <u>[okato]</u><br>
</li>
<li><strong>P/сч.:</strong> <u>[rs]</u>&nbsp;&nbsp; <strong>л/сч. получателя:</strong><u>[lspol]</u> </li>
<li> <strong>в:</strong> <span style="font-size: 90%;"><u>[bank]</u></span><br>
</li>
<li><strong>БИК:</strong> <u>[bik]</u>&nbsp; <strong>К/сч.:</strong><u>[ks]</u><br>
</li>
<li><strong>Код бюджетной классификации (КБК):</strong> <u>[kbk]</u> </li>
<li><strong>Платеж:</strong> <span style="font-size: 90%;"><u>[nums]</u></span><br>
</li>
<li><strong>Плательщик:</strong> <u>[fio]</u><br>
</li>
<li><strong>Адрес плательщика:</strong> <span style="font-size: 90%;"><u>[adres]</u></span><br>
</li>
<li><strong>ИНН плательщика:</strong> <u>[inn]</u>&nbsp;&nbsp;&nbsp;&nbsp; <strong>№ л/сч. плательщика:</strong> <u>[lsplat]</u> </li>
<li><strong>Сумма:</strong> <u>[summa]</u> [valut] 00 коп.<br>
<br>
Подпись:________________________        Дата: [date]<br>
<br>
</li></td></tr><tr><td valign="bottom" height="250" align="center">&nbsp;<strong>Квитанция</strong><br>
<br>
&nbsp;Кассир</td><td valign="top">
<li><strong>Получатель: </strong> <span style="font-size: 90%;"><u>[poluchatel]</u></span>&nbsp;&nbsp;&nbsp;<br>
</li>
<li><strong>КПП:</strong> <u>[kpp]</u>&nbsp;&nbsp;&nbsp;&nbsp; <strong>ИНН:</strong> <u>[inn]</u>&nbsp;&nbsp;&nbsp;&nbsp; <strong>Код ОКАТО:</strong> <u>[okato]</u><br>
</li>
<li><strong>P/сч.:</strong> <u>[rs]</u>&nbsp;&nbsp; <strong>л/сч. получателя:</strong><u>[lspol]</u> </li>
<li><strong>в:</strong> <span style="font-size: 90%;"><u>[bank]</u></span><br>
</li>
<li><strong>БИК:</strong> <u>[bik]</u>&nbsp; <strong>К/сч.:</strong><u>[ks]</u><br>
</li>
<li><strong>Код бюджетной классификации (КБК):</strong> <u>[kbk]</u> </li>
<li><strong>Платеж:</strong> <span style="font-size: 90%;"><u>[nums]</u></span><br>
</li>
<li><strong>Плательщик:</strong> <u>[fio]</u><br>
</li>
<li><strong>Адрес плательщика:</strong> <span style="font-size: 90%;"><u>[adres]</u></span><br>
</li>
<li><strong>ИНН плательщика:</strong> <u>[inn]</u>&nbsp;&nbsp;&nbsp;&nbsp; <strong>№ л/сч. плательщика:</strong> <u>[lsplat]</u> </li>
<li><strong>Сумма:</strong> <u>[summa]</u> [valut] 00 коп.<br>
<br>
Подпись:________________________        Дата: [date]<br>
<br>
</li></td></tr></tbody></table></div>